# .graphqlrc.yml
projects:
  api:
    # schema: "https://api-ap-northeast-1.graphcms.com/v2/ckycgwm2f0e0j01z87bpk18w9/master"
    schema: schema.graphql
    documents: ./src/client/graphql/**/*.graphql
